config/routes.rb
Rails.application.routes.draw do
  root 'drawing_pins#index'
  get '/err', to: 'err#err'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # get 'users/show'

  resources :drawing_pins, only: [:index,:new,:edit,:create,:update,:destroy] do
    collection do
      # ↓一覧画面での検索用
      get :index_search
      # ↓ワークボックスまたはプランから「追加」するか「削除」するかの判断処理用
      get :judge_add_or_remove

      # ↓map上に吹き出しを作成する
      get :make_speech_bubble

      get :tutorial
    end
    # member do
    # end
  end

  resources :workboxes,only:[] do
  #↑二期開発でshowもココに追加する予定 resources :workboxes, only: [:show]
    resources :workbox_pins, only: [:create,:destroy]
  end

  resources :plans, only: [:show,:edit,:update] do
    member do
      get :presentation,:presentation_password
      post :presentation_password_chk
      # ↓一覧画面での検索用
      get :search_pin_for
      # ↓所属するpinについて、経路を一括で変更する
      patch :reset_pin_route
    end



    resources :plan_pins, only: [:show,:new,:edit,:update,:create,:destroy] do
    # resources :plan_pins, only: [:create,:destroy,:show,:new,:edit,:update] do
      collection do
        post :create_in_planform

      end
      member do
        delete :destroy_in_planform
      end
    end

  end

  # ドラッグアンドドロップによるプランピン並び替えの登録用
  patch 'plan/:id/sort', to: 'plans#sort'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations",
  }
  # devise_for :users

  # ユーザープロフィール画面は独自に作成する
  resources :users, only: [:show,:edit,:update]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :torisetu, only: [:index]

end

app/views/layouts/shared/_header.html.erb
<div class="head_bar" href = <%= drawing_pins_path %>>

    <h3 class="head_title">
       <strong >
        <%= link_to drawing_pins_path do %>
           <span class="red"><%= t('title.title_falf_1') %></span><span class="black"><%= t('title.title_falf_2') %></span>
        <% end %>
      </strong>
    </h3>

    <a ><%= t('title.title_sub') %></a>

  <%= link_to t('long_msg.torisetu.about_this_app') ,torisetu_index_path ,class: 'btn btn-primary btn_line_1' %>

</div>

app/views/layouts/shared/_sidebar.html.erb
<div class="sidebar_title">
  <h4 class="form_name"><strong><%= @form_name %></strong></h4>

  <% if @form_name_sub.present? %>
    <strong class="form_name_sub"><%= @form_name_sub %></strong>
  <% end %>
</div>

<% if user_signed_in? %>
  <br><br>
  <%= t('verb.is_login',name: current_user.user_name.to_s) %>

  <br><br>
  <%= link_to t('activerecord.models.user') + t('activerecord.attributes.user.profile'), user_path(current_user.id) %>
  <br><br>

  <% if current_user.tutorial %>
    <%= link_to "ﾁｭｰﾄﾘｱﾙ画面へ" ,tutorial_drawing_pins_path ,class: "btn  btn-primary btn_head" %>
    <br><br>
  <% end %>


  <%= link_to t('verb.make_this',this: t('activerecord.models.drawing_pin')) ,new_drawing_pin_path ,class: "btn  btn-primary btn_head" %>
  <br><br>
  <%= link_to t('verb.look_this',this: t('activerecord.models.drawing_pin')) ,drawing_pins_path ,class: "btn  btn-primary btn_head" %>
  <br>

  <%# ↓作業箱画面は後回し %>
  <%# <%= select :workbox_id,"", get_workboxes_as_selectbox_info[0] ,{:selected => get_workboxes_as_selectbox_info[1]}  %>
  <!-- <br>の作業箱を<a class="btn btn-primary btn-sm" >編集</a> -->

  <br>

  <span data-controller="set-url-by-selectbox">
  <input type="hidden" value= "/plans/" data-target = "set-url-by-selectbox.base_url_1" >
  <input type="hidden" value= "" data-target = "set-url-by-selectbox.base_url_2" >

  <%= select :plan_id,"", get_plans_as_selectbox_info[0] , {:selected => get_plans_as_selectbox_info[1]}, {:data => {:target => "set-url-by-selectbox.selected_info",:action => "change->set-url-by-selectbox#select"},class: "cbb_workbox_or_plan"} %>

  <br><%= t('long_msg.plan.use_plan_1') %><%= link_to t('verb.edit') + t('verb.do'), "" ,class: "btn btn-primary",method: "get" ,:data => {:target => "set-url-by-selectbox.btn"} %>
  </span>

  <br><br>
  <span data-controller="set-url-by-selectbox">
    <input type="hidden" value= "/plans/" data-target = "set-url-by-selectbox.base_url_1" >
    <input type="hidden" value= "/presentation" data-target = "set-url-by-selectbox.base_url_2" >
    <%= select :plan_id,"", get_plans_as_selectbox_info[0],{selected: get_plans_as_selectbox_info[1]}, {:data => {:target => "set-url-by-selectbox.selected_info",:action => "change->set-url-by-selectbox#select"},class: "cbb_workbox_or_plan"} %>

    <br><%= t('long_msg.plan.use_plan_2') %><%= link_to t('verb.purapura') + t('verb.do'), "" ,class: "btn btn-primary",method: "get" ,:data => {:target => "set-url-by-selectbox.btn"} %>
  </span>

  <br>
  <br>

  <div class="hover-balloon"><%= t('long_msg.what_is_plan.msg1') %><br><%= t('long_msg.please_cursor') %>
    <div class="hover-balloon__text">
      <%= t('long_msg.what_is_plan.msg2') %><br>
      <%= t('long_msg.what_is_plan.msg3') %><br>
      <%= t('long_msg.what_is_plan.msg4') %><br>
  　　 <%= t('long_msg.what_is_plan.msg5') %><br>
  　　 <%= t('long_msg.what_is_plan.msg6') %>
    </div>
  </div>

  <br>

  <div class="hover-balloon"><%= t('long_msg.what_is_workbox.msg1') %><br><%= t('long_msg.please_cursor') %>
    <div class="hover-balloon__text">
      <%= t('long_msg.what_is_workbox.msg2') %><br>
      <%= t('long_msg.what_is_workbox.msg3') %><br>
      <%= t('long_msg.what_is_workbox.msg4') %><br>
      <%= t('long_msg.what_is_workbox.msg5') %><br>
  　　 <%= t('long_msg.what_is_workbox.msg6') %>
    </div>
  </div>

  <br>

  <%= t('long_msg.create_plan_and_workbox.msg1') %>
  <br>
  <%= link_to t('long_msg.create_plan_and_workbox.msg2'), edit_user_path(current_user.id) %>
  <br>
  <%= t('long_msg.create_plan_and_workbox.msg3') %>

  <br><br>
  <%= link_to t('verb.logout'), destroy_user_session_path, method: :delete %>

<% else %>

  <br><br>
  <%= t('verb.is_not_login') %>
  <%= link_to "ﾁｭｰﾄﾘｱﾙ画面へ" ,tutorial_drawing_pins_path ,class: "btn  btn-primary btn_head" %>
  <br><br>
  <%= link_to t('verb.make_this',this: t('activerecord.models.drawing_pin')) ,new_drawing_pin_path ,class: "btn  btn-primary btn_head" %>
  <br><br>
  <%= link_to t('verb.look_this',this: t('activerecord.models.drawing_pin')) ,drawing_pins_path ,class: "btn  btn-primary btn_head" %>

  <br><br>
  <%= link_to t('verb.login'), new_user_session_path %>
  <br><br>
  <%= link_to  t('adjective.newly') + t('activerecord.normal_process.noun.save'), new_user_registration_path %>
<% end %>

app/views/layouts/shared/_yahoo_attribution.html.erb
<!-- Begin Yahoo! JAPAN Web Services Attribution Snippet -->
<a href="https://developer.yahoo.co.jp/about">
<img src="https://s.yimg.jp/images/yjdn/yjdn_attbtn2_105_17.gif" width="105" height="17" title="Webサービス by Yahoo! JAPAN" alt="Webサービス by Yahoo! JAPAN" border="0" style="margin:4px 15px 15px 15px"></a>
<!-- End Yahoo! JAPAN Web Services Attribution Snippet -->