config/routes.rb
Rails.application.routes.draw do
  root 'drawing_pins#index'
  get '/err', to: 'err#err'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # get 'users/show'

  resources :drawing_pins, only: [:index,:new,:edit,:create,:update,:destroy] do
    collection do
      # ↓一覧画面での検索用
      get :index_search
      # ↓ワークボックスまたはプランから「追加」するか「削除」するかの判断処理用
      get :judge_add_or_remove

      # ↓map上に吹き出しを作成する
      get :make_speech_bubble

      get :tutorial
    end
    # member do
    # end
  end

  resources :workboxes,only:[] do
  #↑二期開発でshowもココに追加する予定 resources :workboxes, only: [:show]
    resources :workbox_pins, only: [:create,:destroy]
  end

  resources :plans, only: [:show,:edit,:update] do
    member do
      get :presentation,:presentation_password
      post :presentation_password_chk
      # ↓一覧画面での検索用
      get :search_pin_for
      # ↓所属するpinについて、経路を一括で変更する
      patch :reset_pin_route
    end



    resources :plan_pins, only: [:show,:new,:edit,:update,:create,:destroy] do
    # resources :plan_pins, only: [:create,:destroy,:show,:new,:edit,:update] do
      collection do
        post :create_in_planform

      end
      member do
        delete :destroy_in_planform
      end
    end

  end

  # ドラッグアンドドロップによるプランピン並び替えの登録用
  patch 'plan/:id/sort', to: 'plans#sort'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations",
  }
  # devise_for :users

  # ユーザープロフィール画面は独自に作成する
  resources :users, only: [:show,:edit,:update]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :torisetu, only: [:index]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  ####↓↓↓↓バリデーション情報↓↓↓↓############
  validates :user_name, presence: true,uniqueness: true, length: { maximum: 40 }
  validates :account_name, length: { maximum: 20 }
  validates :profile, length: { maximum: 280 }

  validate :check_number_of_workboxes ,on: :update

  def check_number_of_workboxes

    max_workbox_num = 4
    max_plan_num = 24

    #権限保有ユーザーの場合は、登録可能件数は権限テーブルから取得
    role_info = self.role
    if role_info.present?
      max_workbox_num = role_info.max_workbox_num
      max_plan_num = role_info.max_plan_num
    end

    workbox_count = self.workboxes.count{ |workbox| workbox._destroy == false}
    if workbox_count > max_workbox_num
      errors.add(:workbox,"の登録上限数は、4個です。")
    end

    plan_count = self.plans.count{ |plan| plan._destroy == false}
    if plan_count > max_plan_num
      errors.add(:plan,"の登録上限数は、24個です。")
    end


  end
  ####↑↑↑↑バリデーション情報↑↑↑↑############

  ####↓↓↓↓アソシエーション情報↓↓↓↓############
  #削除時にメール送信など行う可能性があるため、delete_allは使わない
  has_many :drawing_pins , dependent: :destroy
  has_many :workboxes , dependent: :destroy
  has_many :plans , dependent: :destroy

  # 一般ユーザーは「対象となる権限レコードなし」の状態とする。
  #ただし権限レコードの削除時は「その権限を有するユーザーがいない」ことが条件
  # (権限削除によって、勝手に一般ユーザーに戻ることはないように)。
  belongs_to :role, optional: true

  # nestedfieldの使用にあたり、↓を追記
  accepts_nested_attributes_for :workboxes, allow_destroy: true
  accepts_nested_attributes_for :plans, allow_destroy: true

  ####↑↑↑↑アソシエーション情報↑↑↑↑############


  #DBに登録してある「（ユーザー情報）公開区分」情報（integer型）から、対応する名称を取得する
  def self.get_public_div_name(n)
      case n
      when 0 then
        return "公開"
      when 9 then
        return "非公開"

      else
        return "不正な値です"
      end

  end

  #DBに登録してある「メールアドレス公開区分」情報（integer型）から、対応する名称を取得する
  def self.get_email_public_div_name(n)
      case n
      when 0 then
        return "公開"
      when 9 then
        return "非公開"

      else
        return "不正な値です"
      end

  end

  #DBに登録してある「ピン公開区分（デフォルト）」情報（integer型）から、対応する名称を取得する
  def self.get_pin_public_div_name(n)
      case n
      when 0 then
        return "公開"
      when 9 then
        return "非公開"

      else
        return "不正な値です"
      end

  end




end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  def destroy
    result = resource.destroy_with_password(destroy_params[:current_password])
    if result
      Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
      set_flash_message :notice, :destroyed
      yield resource if block_given?
      respond_with_navigational(resource){ redirect_to after_sign_out_path_for(resource_name) }
    else
      # パスワード認証に失敗した場合
      resource.errors.add(:password,t('activerecord.errors.messages.restrict_dependent_destroy.is_wrong',record: ""))
      render "/devise/registrations/edit"
      # render edit_user_registration_path
    end
  end

  def destroy_params
    params.require(:user).permit(:current_password)
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

    def after_update_path_for(resource)
      user_path(resource.id)
    end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  include ChkAuthority

  before_action :authenticate_user! ,only: [:edit, :update]
  before_action :authenticate_users_info! ,only: [:edit, :update]
  before_action :authenticate_see_profile! ,only: [:show]

  before_action :set_user, only: [:show, :edit, :update]
  def show
  end

  def edit
  end

  def update
    if @user.update(user_params_for_update)
      redirect_to @user, notice: 'ユーザー情報を変更しました。'
    else
      #エラー情報をフラッシュに保存
      flash[:danger] = @user.errors.full_messages
      render :edit
    end
  end

private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params_for_update
    params_info = params.require(:user).permit(:account_name, :email_public_div, :profile, :public_div, :pin_public_div_default, :tutorial,
        workboxes_attributes: [:id, :workbox_name, :default_box, :_destroy],
        plans_attributes: [:id, :plan_name, :default_plan, :_destroy])

    #「ラジオボックスがoffだった場合」はフォームからは何の値も取得されないので、
    #その場合はここで「標準ではない(=false)」旨を設定する。
    if params_info[:workboxes_attributes].present?
      params_info[:workboxes_attributes].each do |workbox|
        if not (workbox[1][:default_box] == "true")
          workbox[1][:default_box] = "false"
        end
      end
    end

    #「ラジオボックスがoffだった場合」はフォームからは何の値も取得されないので、
    #その場合はここで「標準ではない(=false)」旨を設定する。
    if params_info[:plans_attributes].present?
      params_info[:plans_attributes].each do |plan|
        if not (plan[1][:default_plan] == "true")
          plan[1][:default_plan] = "false"
        end
      end
    end

    return  params_info
  end


  def authenticate_users_info!
    redirect_to err_path if not is_your_info?(model_name: User.name , model_id: params[:id])
  end

  def authenticate_see_profile!
    #プロフィールは「公開」されていれば誰にでも閲覧可能
    #非公開（＝9）の場合のみ、自分（ログイン者）のユーザー情報かチェック
    authenticate_users_info! if set_user.public_div == 9
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<!-- メッセージとか -->
<p id="notice"><%= notice %></p>
<%= render 'layouts/show_danger_msg' %>

<div class="user_form">

  <%= form_with(model: @user, local: true) do |form| %>

    <h3><%=  t('activerecord.models.user') + t('noun.info') +  t('verb.edit') %></h3>

    <div class="line_info">
      <%= form.label t('activerecord.attributes.user.user_name') + "(※)",class: "line_content_1"   %>
      <%= form.label @user.user_name,class: "line_content_2_large_interval"   %>
    </div>

    <div class="line_info">
      <%= form.label :account_name,class: "line_content_1"   %>
      <%= form.text_field :account_name ,class: "line_content_2_large_interval" ,maxlength: 20 %>
    </div>

    <div class="line_info">
      <%= form.label t('activerecord.attributes.user.email') + "(※)",class: "line_content_1"   %>
      <label class="line_content_2_large_interval" ><%= @user.email %></label>
    </div>

    <div class="line_info">
        <%= form.label :email_public_div,class: "line_content_1"    %>

      <span class = "line_content_2_large_interval ">
        <label class = "input_radio_btn">
          <%= form.radio_button :email_public_div, 0 %><%= User.get_email_public_div_name(0) %>
        </label>
        <label class = "input_radio_btn">
          <%= form.radio_button :email_public_div, 9 %><%= User.get_email_public_div_name(9) %>
        </label>
      </span>

    </div>

    <div class="line_info_multiline">
        <%= form.label :profile,class: "line_content_1"    %>
        <%= form.text_area :profile ,class: "line_content_2_large_interval input_text_content",maxlength: 280  %>
    </div>

    <div class="line_info">
        <%= form.label :public_div,class: "line_content_1"    %>

      <span class = "line_content_2_large_interval ">
        <label class = "input_radio_btn">
          <%= form.radio_button :public_div, 0 %><%= User.get_public_div_name(0) %>
        </label>
        <label class = "input_radio_btn">
          <%= form.radio_button :public_div, 9 %><%= User.get_public_div_name(9) %>
        </label>
      </span>

    </div>

    <div class="line_info">
      <label class = "line_content_1">
        ﾁｭｰﾄﾘｱﾙボタンを
      </label>
      <span class = "line_content_2_large_interval"><%= form.check_box :tutorial,:as => :boolean  %>表示する</span>



    </div>

    <div class="line_info">
      <%= form.label :pin_public_div_default,class: "line_content_1" %>

      <span class = "line_content_2_large_interval ">
        <label class = "input_radio_btn">
          <%= form.radio_button :pin_public_div_default, 0 %><%= User.get_pin_public_div_name(0) %>
        </label>
        <label class = "input_radio_btn">
          <%= form.radio_button :pin_public_div_default, 9 %><%= User.get_pin_public_div_name(9) %>
        </label>
        <label ><%= t('long_msg.user.pin_public_description')%></label>
      </span>

    </div>


    <div class="line_info">
    </div>

    <div class="line_info">
      <%= form.label t('long_msg.user.are_important.msg1')  %>
      <%= form.label t('long_msg.user.are_important.msg2')  %>
    </div>

    <div class="line_info">
      <%= form.label t('long_msg.user.max_plans_and_workboxes'),class: "line_content_1"   %>
    </div>

  <div class="users_twin_box">
    <div class="users_box_alone">
      <div class="line_info">
        <h4 class="users_box_title"><%=  t('activerecord.models.workbox') %></h4><%= form.add_nested_fields_link :workboxes, t('activerecord.models.workbox') + t('verb.add'), class: 'btn btn-primary line_content_btn', role: 'button', data: { limit: 4 } %>
      </div>

      <table class="table table-striped table-bordered table-hover users_box_table" data-controller="select-one-btn">
        <tbody>
          <tr>
             <th><%=  t('activerecord.attributes.workbox.workbox_name') %></th>
             <th><%=  t('activerecord.attributes.workbox.default_box') %></th>
             <th></th>
          </tr>
          <%= form.nested_fields_for :workboxes, wrapper_tag: :tr do |q| %>
              <td><%= q.text_field   :workbox_name,     class: 'form-control' %></td>
              <td><%= q.radio_button :default_box, true , class: 'form-control',:data => {:action => "change->select-one-btn#change_btn", :target => "select-one-btn.btn"} %></td>
              <td><%= q.remove_nested_fields_link t('verb.del'), class: 'btn btn-danger', role: 'button' %></td>
          <% end %>
        </tbody>
      </table>

    </div>

    <div class="users_box_alone">

      <div class="line_info">
        <h4 class="users_box_title"><%=  t('activerecord.models.plan') %></h4><%= form.add_nested_fields_link :plans, t('activerecord.models.plan') + t('verb.add'), class: 'btn btn-primary line_content_btn', role: 'button' %>
      </div>

      <table class="table table-striped table-bordered table-hover users_box_table" data-controller="select-one-btn">
        <tbody>
          <tr>
            <th><%=  t('activerecord.attributes.plan.plan_name') %></th>
            <th><%=  t('activerecord.attributes.plan.default_plan') %></th>
            <th></th>
          </tr>
          <%= form.nested_fields_for :plans, wrapper_tag: :tr do |q| %>
            <td><%= q.text_field   :plan_name,     class: 'form-control' %></td>
            <td><%= q.radio_button :default_plan, true , class: 'form-control',:data => {:action => "change->select-one-btn#change_btn", :target => "select-one-btn.btn"} %></td>
            <td><%= q.remove_nested_fields_link t('verb.del'), class: 'btn btn-danger', role: 'button' %></td>
          <% end %>
        </tbody>
      </table>

    </div>

  </div>

  <div class="line_info">
    <%= form.submit  t('activerecord.normal_process.noun.save') , class: 'btn btn-primary line_content_btn'%>
  </div>

  <% end %>
</div>

app/views/users/show.html.erb
<!-- メッセージとか -->
<p id="notice"><%= notice %></p>
<%= render 'layouts/show_danger_msg' %>

<div class="user_form">

  <h2><%= t('activerecord.models.user') + t('activerecord.attributes.user.profile') %></h2>

  <div class="line_info">
    <div class="line_content_1">
      <strong><%= t('activerecord.attributes.user.account_name') %>:</strong>
      <%= @user.account_name %>
    </div>
  </div>

  <div class="line_info">
    <div class="line_content_1">
      <strong><%= t('activerecord.attributes.user.user_name') %>:</strong>
      <%= @user.user_name %>
    </div>
  </div>

  <div class="line_info">
    <div class="line_content_1">
      <strong><%= t('activerecord.attributes.user.email') %>:</strong>

      <% if (user_signed_in? && @user.id == current_user.id) || (@user.email_public_div == 0) %>
        <%= @user.email %>
      <% else %>
        <%= t('activerecord.attributes.user.public_div_type.type_9') %>
      <% end %>
    </div>
  </div>

  <div class="line_info">
    <div class="user_profile_show ">
      <strong><%= t('activerecord.attributes.user.profile') %>:</strong>
      <%= @user.profile %>
    </div>
  </div>

  <div class="line_info">
  </div>
  <div class="line_info">
  </div>

  <% if user_signed_in? && @user.id == current_user.id %>

  <div class="line_info">
    <%= link_to "#{t('activerecord.attributes.user.profile')}#{t('verb.change')}、「#{t('activerecord.models.workbox')}」「#{t('activerecord.models.plan')}」#{t('verb.organize')}", edit_user_path(@user.id), class: 'btn btn-primary btn_line_1' %>
  </div>

  <div class="line_info">
    <%= link_to "#{t('activerecord.attributes.user.password')}、#{t('activerecord.attributes.user.user_name')}#{t('verb.change')}", edit_user_registration_path(@user.id), class: 'btn btn-primary btn_line_1'  %>
  </div>

  <% end %>

  <div class="line_info">
    <div class="line_content_1">
      【公開しているプラン】
    </div>
  </div>

  <table class = "plofile_plan_index" >
    <thead>
      <tr>
        <th class = "plofile_plan_index_image">画像</th>
        <th class = "plofile_plan_index_name">名称</th>
        <th class = "plofile_plan_index_comment">概要</th>

        <% if user_signed_in? && @user.id == current_user.id %>
          <th colspan="2"></th>
        <% else %>
          <th colspan="1"></th>
        <% end %>

      </tr>
    </thead>

    <tbody>
      <% @user.plans.where(public_div: 0).order(:created_at).each do |plan| %>
        <tr>

          <td class = "plofile_plan_index_image">
            <% if plan.image && plan.image.url %>
              <%= image_tag(plan.image.url,class: 'index_grid_item_imagecontent' )  %>
            <% else %>
              <span class = 'index_grid_item_imagecontent'>プラン画像未登録</span>
            <% end %>
          </td>

          <td class = "plofile_plan_index_name"><%= plan.plan_name %></td>
          <td class = "plofile_plan_index_comment"><%= plan.comment %></td>

          <td class = "plofile_plan_index_btn"><%= link_to 'ぷらぷらする', presentation_plan_path(plan.id) ,class: "btn btn-primary" %></td>

          <% if user_signed_in? && @user.id == current_user.id %>
            <td class = "plofile_plan_index_btn"><%= link_to 'プラン編集', plan_path(plan.id) ,class: "btn btn-primary" %></td>
          <% end %>

        </tr>
      <% end %>
    </tbody>
  </table>

</div>