config/routes.rb
Rails.application.routes.draw do
  root 'drawing_pins#index'
  get '/err', to: 'err#err'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # get 'users/show'

  resources :drawing_pins, only: [:index,:new,:edit,:create,:update,:destroy] do
    collection do
      # ↓一覧画面での検索用
      get :index_search
      # ↓ワークボックスまたはプランから「追加」するか「削除」するかの判断処理用
      get :judge_add_or_remove

      # ↓map上に吹き出しを作成する
      get :make_speech_bubble

      get :tutorial
    end
    # member do
    # end
  end

  resources :workboxes,only:[] do
  #↑二期開発でshowもココに追加する予定 resources :workboxes, only: [:show]
    resources :workbox_pins, only: [:create,:destroy]
  end

  resources :plans, only: [:show,:edit,:update] do
    member do
      get :presentation,:presentation_password
      post :presentation_password_chk
      # ↓一覧画面での検索用
      get :search_pin_for
      # ↓所属するpinについて、経路を一括で変更する
      patch :reset_pin_route
    end



    resources :plan_pins, only: [:show,:new,:edit,:update,:create,:destroy] do
    # resources :plan_pins, only: [:create,:destroy,:show,:new,:edit,:update] do
      collection do
        post :create_in_planform

      end
      member do
        delete :destroy_in_planform
      end
    end

  end

  # ドラッグアンドドロップによるプランピン並び替えの登録用
  patch 'plan/:id/sort', to: 'plans#sort'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations",
  }
  # devise_for :users

  # ユーザープロフィール画面は独自に作成する
  resources :users, only: [:show,:edit,:update]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :torisetu, only: [:index]

end

app/models/plan.rb
class Plan < ApplicationRecord

  #「image」列を、画像アップローダと紐付ける
  mount_uploader :image, ImageUploader

  has_secure_password validations: false

  ####↓↓↓↓バリデーション情報↓↓↓↓############
  validates :plan_name, presence: true, length: {maximum:20}

  # プランパスワードのチェックは「40文字以下」だけ……未入力チェックは「chk_password_existence」で行う
  validates :password ,length: {maximum: 40}

  #パスワードの存在確認……
  validate :chk_password_existence, on: :update

  validates :comment ,length: {maximum: 40}

  def chk_password_existence

    case self.public_div
    when 0
      # 「公開」にする場合はパスワードを空にする
      self.password_digest = nil
    when 9
      # 「非公開」にする場合はパスワード必須（なければエラー）
      errors.add(:password,"「非公開」にする場合はパスワードを設定してください。") if self.password_digest.blank?
    end
  end
  ####↑↑↑↑バリデーション情報↑↑↑↑############

  ####↓↓↓↓アソシエーション情報↓↓↓↓############
  belongs_to :user

  # 「参照するworkbox情報」を持つことができるだけ。
  # 持たないこともできるし、workboxが消えてもplanは消さない。
  belongs_to :workbox, optional: true

  #'acts_as_list'導入による変更
  has_many :plan_pins, -> { order(position: :asc) }, dependent: :destroy
  # has_many :plan_pins, dependent: :destroy

  # has_many :plan_pins, -> { order(position: :asc) }

  # has_many :plan_pins, -> { order(position: :asc) } , dependent: :destroy

  # has_many :plan_pins , dependent: :destroy

  ####↑↑↑↑アソシエーション情報↑↑↑↑############

  ##所属しているピンの経路情報を一括で更新（リセット）する
  def reset_route(route_info)

    if route_info == ""
      errors.add(:route , "経路を選択してください。")
      return false
    end

    if not ["0","1","2","3"].include?(route_info)
      errors.add(:route , "経路が不正です。")
      return false
    end

    plan_pins.update_all(route: route_info)

    return true

  end

end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  include GetPinForPlanShow
  include GetReplacedPinInfo
  include ChkAuthority

  before_action :authenticate_user!, if: :not_presentation?
  before_action :authenticate_users_info!, if: :not_presentation?
  before_action :authenticate_presentation!, only: [:presentation]

  before_action :set_presentation_view_form_type, only: [:presentation]


  def show
    set_plan
    @form_name=t('activerecord.models.plan') + t('verb.edit')
    @form_name_sub="(#{@plan.plan_name})"

    #プランが保有しているピン情報
    condition = {plan_id: params[:id]}
    @plan_pins = select_pin_as_plan_member(condition,for_json: true)
    # @plan_pins = select_pin_as_plan_member(params[:id],for_json: true)
    # 配列をJsonへ変換する
    @plan_pins_json = @plan_pins.to_json.html_safe

    #初期表示時は、「まだプランに追加されていないピン」は検索されないようにする
    @drawing_pins = DrawingPin.none
    # 配列をJsonへ変換する
    @drawing_pins_json = @drawing_pins.to_json.html_safe

  end

  def search_pin_for

    #検索時は「プラン」「プランピン」もデータベースから再取得
    #……「プランピン」の登録，削除後も再検索して表示し直すため。
    @plan = Plan.find(params[:id])
    #プランが保有しているピン情報
    condition = {plan_id: params[:id]}
    @plan_pins = select_pin_as_plan_member(condition,for_json: true)

    # 配列をJsonへ変換する
    @plan_pins_json = @plan_pins.to_json.html_safe

    #まだプランに追加されていないピン（検索
    @drawing_pins = select_pin_as_plan_candidate(params[:conditions],for_json: true)
    # 配列をJsonへ変換する
    @drawing_pins_json = @drawing_pins.to_json.html_safe

    respond_to do |format|
      format.js { render :search_and_index }
    end

  end

  def sort
    @plan = Plan.find(params[:id])
    plan_pin = @plan.plan_pins[params[:from].to_i]
    plan_pin.insert_at(params[:to].to_i + 1)
    head :ok
  end

  def edit
    @form_name=t('activerecord.models.plan') + t('noun.contents') + t('activerecord.normal_process.noun.update')
    set_plan

    if session["edit_plan"].present?
      #session情報がある場合はそれを取得して、取得したsessionはクリアする（エラー発生によりredirect_toした場合の処理）
      @plan = Plan.new(session["edit_plan"])

      session["edit_plan"] = nil
    end
  end

  def update
    set_plan

    if not params[:plan][:password] == params[:plan][:password_confirmation]
      #入力情報をセッション、エラー情報をフラッシュに保存して
      session["edit_plan"] = @plan
      flash[:danger] = [t('activerecord.attributes.plan.password') + t('errors.messages.confirmation',attribute: t('activerecord.attributes.plan.password_confirmation'))]
      # ["Password confirmationとPasswordの入力が一致しません"]

      redirect_to edit_plan_path(@plan)
    else

      if @plan.update(plan_params_with_pass)
        redirect_to edit_plan_path(@plan.id), notice: t('activerecord.normal_process.messages.do_save')
      else
        #入力情報をセッション、エラー情報をフラッシュに保存して
        session["edit_plan"] = @plan
        flash[:danger] = @plan.errors.full_messages
        redirect_to edit_plan_path(@plan)
      end

    end

  end


  def reset_pin_route
  # 所属しているピンの経路を一括で変更する
    set_plan

    if @plan.reset_route(params[:plan][:route])
      flash[:notice] = "所属している📍の経路を再設定しました。"
    else
      flash[:danger] = @plan.errors.messages[:route]
    end

    # respond_to do |format|
    #   format.js { render :reset_pin_route }
    # end

  end


  def presentation
    set_plan

    @pins_belongs_to_plan = select_pins_belongs_to_plan(@plan.id,for_json: true)
    @pins_belongs_to_plan_json = @pins_belongs_to_plan.to_json.html_safe

    if @plan.workbox_id.present?
      @pins_belongs_to_workbox = select_pins_belongs_to_workbox_for_plan(@plan.id,@plan.workbox_id,for_json: true)
    else
      @pins_belongs_to_workbox = DrawingPin.none
    end
    # 配列をJsonへ変換する
    @pins_belongs_to_workbox_json = @pins_belongs_to_workbox.to_json.html_safe

  end

  def presentation_password
    #プレゼン前の、パスワード確認画面（公開区分が「9:非公開」の場合のみ通る
    set_plan
    @form_name=t('activerecord.attributes.plan.password') + t('verb.confirm')
    @form_name_sub="(#{@plan.plan_name})"
  end

  def presentation_password_chk
    #プレゼン前の、パスワード照合（公開区分が「9:非公開」の場合のみ通る
    set_plan
    if @plan.authenticate(params[:plan][:password]) == false
      #パスワードが違っていた場合
      flash[:danger] = [t('long_msg.plan.password.not_match.msg1'),t('long_msg.plan.password.not_match.msg2')]
      # flash[:danger] = ["パスワードが一致しません。確認して再入力して下さい。","（プラン作成者はプラン更新画面でパスワード再設定可能です）。"]
      redirect_to presentation_password_plan_path(params[:id])
    else
      #入力されたパスワードが合っていた場合
      session["presentation_#{params[:id]}"] = "OK"
      redirect_to presentation_plan_path(params[:id])
    end
  end

  private

  def set_plan
    @plan = Plan.find(params[:id])
  end

  def plan_params
    params.require(:plan).permit(:user_id, :plan_name, :default_plan, :public_div,:image,:remove_image,:comment)
  end

  # パスワードが設定されていた場合はパスワードも更新
  def plan_params_with_pass
    params.require(:plan).permit(:plan_name, :public_div, :workbox_id,:password, :password_confirmation,:image,:remove_image,:comment)
  end

  def set_presentation_view_form_type
    #view_form_type→0：通常画面（サイドバーあり）、1：プレゼン用画面（サイドバーなし）
    @view_form_type = 1
  end

  def not_presentation?
    return (not ["presentation","presentation_password","presentation_password_chk"].include?(action_name))
  end

  def authenticate_users_info!
    redirect_to err_path if not is_your_info?(model_name: Plan.name , model_id: params[:id])
  end

  def authenticate_presentation!
    if session["presentation_#{params[:id]}"].present?
      #session情報がある(=プレゼン用パスワード確認画面を通ってきた)場合は

      #セッション情報を削除して、そのまま表示
      session["presentation_#{params[:id]}"] = nil
    else
      #プランの公開区分が「9：非公開」の場合は、いったん「プレゼン用パスワード確認画面」を通す
      redirect_to presentation_password_plan_path(params[:id]) if set_plan.public_div == 9
    end
  end

end

app/helpers/plans_helper.rb
module PlansHelper

  #セレクトボックス作成のために、（引数がTならば現在ユーザーの）プラン情報を取得
  def get_plans_as_selectbox_info(only_currentuser: true , has_blank: false)
    if only_currentuser
      plans = Plan.where(user_id: current_user.id).order(:created_at)
    else
      plans = Plan.all.order(:created_at)
    end

    if has_blank==true
      box_info = plans.map{|plan| [plan.plan_name,plan.id]}.unshift(["",""])
    else
      box_info = plans.map{|plan| [plan.plan_name,plan.id]}
    end

    #初期選択情報を取得
    if only_currentuser
      default_info = current_user.plans.find_by(default_plan: true)
      if default_info.blank?
        default_info = ""
      else
        default_info = default_info.id
      end
    else
      default_info = ""
    end

    return [box_info,default_info]

  end

end

app/views/plans/_plan_index_item.html.erb
<%# item_type:「0」→グリッド欄のアイテム、「１」→地図上の吹きだし %>

<% if item_type == 0 %>

  <input name="latitude" type="hidden" data-target = "pin-and-planpin.latitude" value= <%= plan_pin.latitude %>  data-action-pin-id = <%= plan_pin.drawing_pin_id.to_s %> >
  <input name="longitude" type="hidden" data-target = "pin-and-planpin.longitude" value= <%= plan_pin.longitude %>  data-action-pin-id = <%= plan_pin.drawing_pin_id.to_s %> >

<% end %>

<!-- <div class="index_grid_item"> -->
  <div class="index_grid_item_head">
    <a><%= plan_pin.pin_name %></a>
  </div>

  <div class="index_grid_item_body">

    <% if item_type == 0 %>
      <div class="index_grid_item_body_left" data-action = "click->pin-and-planpin#move" data-action-pin-id = <%= plan_pin.drawing_pin_id.to_s %> >
    <% else %>
      <div class="index_grid_item_body_left" >
    <% end %>

      <% if plan_pin.drawing_pin.image && plan_pin.drawing_pin.image.url %>
        <%= image_tag(plan_pin.drawing_pin.image.url,class: 'index_grid_item_imagecontent')  %>
      <% else %>
        <a class="index_grid_item_imagecontent" >画像未登録</a>
      <% end %>
    </div>

    <div class="index_grid_item_body_right">
      <strong>【記事】：</strong><%= plan_pin.pin_article %>
    </div>
  </div>

  <div class="index_grid_item_line_1" >

  </div>

  <div class="index_grid_item_line_2" >
    <a class="btn btn-primary btn-sm" >更新</a>
    <a class="btn btn-primary btn-sm" >削除</a>
  </div>

app/views/plans/_search_and_index.html.erb
<div class="search_result_container"   data-controller="pin-and-planpin">
<!-- <div class="search_result_container"   data-controller="pin-index">   -->

<%# データコントローラ「pin-and-planpin」についてのメモ  %>
<%# 目的→  地図に「プランのピン」「プランに所属していないピン」を表示する%>
<%# ターゲット→　「pins_not_plan：プランに所属していないピン」「plan_pins：プランのピン」「map：地図」  %>
<%# アクション→  %>

  <input name="maps_json" type="hidden" data-target = "pin-and-planpin.plan_id" value= <%= plan.id %> >
  <input name="maps_json" type="hidden" data-target = "pin-and-planpin.pins_not_plan" value= <%= drawing_pins_json %> >
  <input name="maps_json" type="hidden" data-target = "pin-and-planpin.plan_pins" value= <%= plan_pins_json %> >

  <div class="index_map_container">

    <div id = "main_index_map" class="index_map_box" data-target="pin-and-planpin.map">
    </div>

    <div class="index_map_instructions">
      <%= render 'layouts/shared/yahoo_attribution' %>
      <br>
      <div>
        ・<span class="pin_sample_blue"></span><%= t('long_msg.pin.blue_pin_description',plan_name: plan.plan_name ) %>
      </div>
        <br>
      <div>
        ・<span class="pin_sample_red"></span><%= t('long_msg.pin.red_pin_description') %>
      </div>
    </div>
  </div>

  <div class="index_grid_box">
    <div class="index_grid_head">
      
      <div class="index_grid_head_description">
        <%= t('activerecord.models.plan') %>：<%= link_to plan.plan_name ,edit_plan_path(plan.id) ,class: "btn btn-primary" %><%= t('connection_word.betongs_to', this: t('activerecord.models.drawing_pin')) + t('form.type.list') %>
        <div>
          <%= t('long_msg.pin.please_click_image.msg2') %>
        </div>
        <div>
          <%= t('long_msg.plan.please_sort_pin') %>
        </div>
      </div>

    </div>

    <div class="index_grid_body"  id="sortable_list">
      <% plan_pins.each_with_index do |plan_pin| %>
        <div id = "pin_id_<%= plan_pin.drawing_pin_id %>" class="index_grid_item">
          <div hidden>plan_pin</div>
          <%= render 'plan_pins/show',plan: plan , plan_pin: plan_pin ,item_type: 0 %>
          <%# <%= render 'plan_index_item', plan_pin: plan_pin , item_num: i ,item_type: 0 %>
          <%# item_type:「0」→グリッド欄のアイテム、「１」→地図上の吹き出し %>

        </div>
      <% end %>
    </div>
    <% if plan_pins.size > 0 %>
      <%= hidden_field_tag :plan_id, plan_pins[0].plan_id %>
    <% end %>

  </div>

</div>

app/views/plans/edit.html.erb
<!-- メッセージとか -->
<p id="notice_msg"><%= render 'layouts/show_notice_msg' %></p>
<p id="danger_msg"><%= render 'layouts/show_danger_msg' %></p>

<%= form_with(model: @plan,url: plan_path, method: :patch , local: true) do |form| %>

  <div class="line_info">
    <%= form.label :plan_name,class: "line_content_1"  %>
    <%= form.text_field :plan_name,class: "line_content_2" %>
  </div>

  <div class="line_info">
    <%= form.label "概要",class: "line_content_1"  %>
    <%= form.text_field :comment,class: "line_content_2" ,maxlength: 40 %>
  </div>

  <div class="line_info">
    <%= form.label :workbox ,class: "line_content_1"  %>
    <%= form.select :workbox_id, get_workboxes_as_selectbox_info(has_blank: true)[0],{},class: "line_content_2"  %>
  </div>

  <span data-controller="password-change-or-not">

    <div class="line_info">
      <%= form.label :public_div,class: "line_content_1"  %>

      <span class = "input_radio_btn_line">
        <label class = "input_radio_btn">
          <%= form.radio_button :public_div, 0 ,:data => {:action => "change->password-change-or-not#check",:target => "password-change-or-not.check"}%><%= t('activerecord.attributes.plan.public_div_type.type_0') %>
        </label>
        <label class = "input_radio_btn">
          <%= form.radio_button :public_div, 9 ,:data => {:action => "change->password-change-or-not#check",:target => "password-change-or-not.check"}%><%= t('activerecord.attributes.plan.public_div_type.type_9') %>
        </label>
      </span>

    </div>
    <div class="line_info">
      <%= form.label t('long_msg.plan.password.setting_info.msg1'),class: "line_conten_annotation"%>
    </div>

    <div class="line_info">
      <%= form.label  :password,class: "line_content_1"%>
      <%= form.password_field :password, value: "", class: "line_content_2",:data => {:target => "password-change-or-not.password"} %>
    </div>

    <div class="line_info">
      <%= form.label :password,class: "line_content_1"%>
      <%= form.password_field :password_confirmation, value: "", class: "line_content_2",:data => {:target => "password-change-or-not.password_confirmation"}  %>
        <%= form.label "(#{t('verb.for_confirm')})",class: "line_content_password_confirm_annotation"%>
    </div>

  </span>

  <div class="line_info">
    <%= form.label t('long_msg.plan.password.setting_info.msg2'),class: "line_conten_annotation"%>
    <%= form.label t('long_msg.plan.password.setting_info.msg3'),class: "line_conten_annotation"%>
    <%= form.label t('long_msg.plan.password.setting_info.msg4'),class: "line_conten_annotation"%>
  </div>

  <div class="line_info">
  </div>

  <div  data-controller="save-image">
    <div class="line_info">
      <%# ↓エラーメッセージ等表示枠 %>
      <a  data-target="save-image.msg"></a>
    </div>

    <div class="line_info">
      <%= form.label "プラン画像" ,class: "line_content_1" %>
      <%= form.file_field :image, id: :image ,class: "line_content_2" , :data => {:action => "change->save-image#change_image" , :target =>"save-image.file_field"}%>
    </div>

    <% if form.object.image && form.object.image.url %>

      <div class="line_info">
        <span class = "line_content_1" >
          <%= form.check_box :remove_image %>
          <%= form.label "プラン画像を削除する" %>
        </span>
      </div>

    <%  end %>

    <div id="image_field_plan_edit" data-target = "save-image.image_field" class = "image_field_plan_edit" >

        <% if form.object.image && form.object.image.url %>
          <%= image_tag(form.object.image.url ,class: "image_field_preview")%>
        <%  end %>

    </div>

  </div>

  <div class="line_info">
    <%= form.submit id:"btn_save" , class: 'btn btn-primary line_content_btn'%>
  </div>

<% end %>

<!-- メッセージとか -->
<p id="route_notice_msg"><%= render 'layouts/show_notice_msg' %></p>
<p id="route_danger_msg"><%= render 'layouts/show_danger_msg' %></p>

<h4>【経路一括設定】</h4>
<%= form_with(model: @plan,url: reset_pin_route_plan_path, method: :patch , remote: true) do |form| %>

  <div class="line_info">

    所属する📍間の経路を、全て
    <%= form.select :route, get_routes_as_selectbox_info(has_blank: true) %>
    に
    <%= form.submit "変更"  %>
    する。
  </div>

<% end %>

app/views/plans/presentation.html.erb
<div class="presentation" data-controller="presentation">

  <input name="maps_json" type="hidden" data-target = "presentation.plan_id" value= <%= @plan.id %> >
  <input name="maps_json" type="hidden" data-target = "presentation.pins_belongs_to_plan" value= <%= @pins_belongs_to_plan_json %> >
  <input name="maps_json" type="hidden" data-target = "presentation.pins_belongs_to_workbox" value= <%= @pins_belongs_to_workbox_json %> >

  <div id="masin_map" class="presentation_map" data-target="presentation.map">

  </div>

  <div class="presentation_underform">
    <div class="presentation_attribution">

      <%= render 'layouts/shared/yahoo_attribution' %>
    </div>

    <div class="presentation_title_and_index">

      <h5 class="presentation_title"><%= "【#{@plan.plan_name}】" %></h5>

      <div class="presentation_index">

        <% @pins_belongs_to_plan.each_with_index do |plan_pin,i| %>

          <div class="presentation_index_item" data-target = "presentation.index_item"  data-action = "click->presentation#move"  data-action-index-num = <%= i.to_s %> >

            <% if plan_pin.url.blank? %>
              <a  class="index_grid_item_presen_title"><%= "#{(i + 1).to_s}:" + plan_pin.pin_name.truncate(8) %></a>
            <% else %>
              <%= link_to "#{(i + 1).to_s}:" + plan_pin.pin_name.truncate(8), plan_pin.url , :target=>["_blank"], class: "index_grid_item_presen_title_withlink" %>
            <% end %>

            <div class="index_grid_item_presen_image">

              <% if plan_pin.image && plan_pin.image.url %>
                <%= image_tag(plan_pin.image.url,class: 'index_grid_item_imagecontent')  %>
              <% else %>
                <a class="index_grid_item_presen_imagecontent" ><%=  t('activerecord.attributes.drawing_pin.no_image.not_set') %></a>
              <% end %>
            </div>

            <div class="index_grid_item_presen_article">
              <%= plan_pin.pin_article.truncate(22) %>
            </div>


          </div>

        <% end %>

      </div>
      <a class='btn btn-default btn_presentation_move_most btn_move_to_leftmost ' data-action="presentation#move_to_leftmost" ><span class="btn_move_content">◀◀</span></a>

      <a class='btn btn-default btn_presentation_move btn_move_to_left ' data-action="presentation#move_to_left" ><span class="btn_move_content">◀</span></a>

      <a class='btn btn-default btn_presentation_move btn_move_to_right ' data-action="presentation#move_to_right" ><span class="btn_move_content">▶</span></a>

      <a class='btn btn-default btn_presentation_move_most btn_move_to_rightmost ' data-action="presentation#move_to_rightmost" ><span class="btn_move_content">▶▶</span></a>

    </div>

  </div>

</div>

app/views/plans/presentation_password.html.erb
<h4><%= t('long_msg.plan.password.please_input') %></h4>
<!-- メッセージとか -->
<p id="notice_msg"><%= render 'layouts/show_notice_msg' %></p>
<p id="danger_msg"><%= render 'layouts/show_danger_msg' %></p>

<%= form_with(model: @plan , method: :post ,url: presentation_password_chk_plan_path, local: true) do |form| %>

  <%= form.label :password %>
  <%= form.password_field :password ,id: :password  %>

  <%= form.submit t('verb.confirm') ,id: "btn_confirm" %>
<% end %>

app/views/plans/reset_pin_route.js.erb
$("#route_notice_msg").html("<%= j(render 'layouts/show_notice_msg') %>")

$("#route_danger_msg").html("<%= j(render 'layouts/show_danger_msg') %>")

app/views/plans/reset_search_and_index.js.erb
// 「検索ボタンをクリック」により再検索
var btn_search = document.getElementById("btn_search");
btn_search.click();

// メッセージを表示する
$("#notice_msg").html("<%= j(render 'layouts/show_notice_msg') %>")

$("#danger_msg").html("<%= j(render 'layouts/show_danger_msg') %>")

app/views/plans/search_and_index.js.erb
$("#search_and_index").html("<%= j(render 'plans/search_and_index', {plan: @plan,plan_pins: @plan_pins, plan_pins_json: @plan_pins_json , drawing_pins: @drawing_pins , drawing_pins_json: @drawing_pins_json}) %>")

var el, sortable;
el = document.getElementById("sortable_list");
if (el !== null) {
  sortable = Sortable.create(el, {
    delay: 80,
    onUpdate: function(evt) {
        return $.ajax({
          url: '/plan/' + $("#plan_id").val() + '/sort',
          type: 'patch',
          data: {
            from: evt.oldIndex,
            to: evt.newIndex
          }
        });
    }
  });
};

app/views/plans/show.html.erb
<div>

  <div class="index_search_box">
  【<%= t('noun.search_condition') %>】
    <%= form_with scope: :conditions, url:search_pin_for_plan_path,method: :get ,remote: true do |form| %>

      <div class="index_search_line">
        <div class="index_search_item">
          <%= t('activerecord.models.workbox') %><%= form.select :workbox_id , get_workboxes_as_selectbox_info(has_blank: true)[0] ,selected: @plan.workbox_id %>
        </div>
        <div class="index_search_item">

          <%= form.label t('activerecord.attributes.common_matter.created_at')%>
          <%= form.date_field :created_at_from %>
          <%= form.label "〜"%>
          <%= form.date_field :created_at_to %>
        </div>
      </div>

      <div class="index_search_line">

        <div class="index_search_item">

          <%= form.label t('activerecord.attributes.user.user_name')%>

          <% if user_signed_in? %>
            <%= form.text_field :user_name ,value: current_user.user_name %>
          <% else %>
            <%= form.text_field :user_name  %>
          <% end %>
        </div>
        <div class="index_search_item">

          <%= form.label t('activerecord.attributes.common_matter.updated_at')%>
          <%= form.date_field :updated_at_from %>
          <%= form.label "〜"%>
          <%= form.date_field :updated_at_to %>
        </div>
      </div>

      <div class="index_search_line">

        <div class="index_search_item">

          <%= form.label t('activerecord.attributes.drawing_pin.pin_name')%>
          <%= form.text_field :pin_name %>

        </div>
        <div class="index_search_item">
        <%= form.label t('activerecord.attributes.drawing_pin.address')%>
          <%= form.text_field :address %>
        </div>
      </div>


      <div class="index_search_line">

        <div class="index_search_item">

          <%= form.label t('activerecord.attributes.drawing_pin.pin_article')%>
          <%= form.text_field :pin_article %>
        </div>
        <div class="index_search_item">

        </div>
      </div>

      <div class="index_search_line">

        <div class="index_search_item">
        </div>
        <div class="index_search_item">

          <%= form.hidden_field :plan_id ,value: @plan.id  %>
          <%= form.submit t('noun.search') , id: "btn_search" , class: 'btn btn-primary btn_line_2'  %>

        </div>
      </div>


    <% end %>
  </div>

  <!-- メッセージとか -->
  <p id="notice_msg"><%= render 'layouts/show_notice_msg' %></p>
  <p id="danger_msg"><%= render 'layouts/show_danger_msg' %></p>

  <div id="search_and_index">

    <%= render 'search_and_index',plan: @plan, plan_pins: @plan_pins, plan_pins_json: @plan_pins_json , drawing_pins: @drawing_pins, drawing_pins_json: @drawing_pins_json %>

  </div>

</div>