config/routes.rb
Rails.application.routes.draw do
  root 'drawing_pins#index'
  get '/err', to: 'err#err'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # get 'users/show'

  resources :drawing_pins, only: [:index,:new,:edit,:create,:update,:destroy] do
    collection do
      # ↓一覧画面での検索用
      get :index_search
      # ↓ワークボックスまたはプランから「追加」するか「削除」するかの判断処理用
      get :judge_add_or_remove

      # ↓map上に吹き出しを作成する
      get :make_speech_bubble

      get :tutorial
    end
    # member do
    # end
  end

  resources :workboxes,only:[] do
  #↑二期開発でshowもココに追加する予定 resources :workboxes, only: [:show]
    resources :workbox_pins, only: [:create,:destroy]
  end

  resources :plans, only: [:show,:edit,:update] do
    member do
      get :presentation,:presentation_password
      post :presentation_password_chk
      # ↓一覧画面での検索用
      get :search_pin_for
      # ↓所属するpinについて、経路を一括で変更する
      patch :reset_pin_route
    end



    resources :plan_pins, only: [:show,:new,:edit,:update,:create,:destroy] do
    # resources :plan_pins, only: [:create,:destroy,:show,:new,:edit,:update] do
      collection do
        post :create_in_planform

      end
      member do
        delete :destroy_in_planform
      end
    end

  end

  # ドラッグアンドドロップによるプランピン並び替えの登録用
  patch 'plan/:id/sort', to: 'plans#sort'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations",
  }
  # devise_for :users

  # ユーザープロフィール画面は独自に作成する
  resources :users, only: [:show,:edit,:update]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :torisetu, only: [:index]

end

app/models/plan_pin.rb
class PlanPin < ApplicationRecord

  belongs_to :plan
  acts_as_list scope: :plan
  #'↑acts_as_list'導入に伴う追加記述

  ####↓↓↓↓バリデーション情報↓↓↓↓############
  validates :plan_pin_name, presence: true, length: {maximum:30}
  validates :plan_pin_article, length: {maximum:180}
  validates :plan_id,  uniqueness: { scope: :drawing_pin_id}
  ####↑↑↑↑バリデーション情報↑↑↑↑############

  before_validation :set_pin_info ,on: :create

  ####↓↓↓↓アソシエーション情報↓↓↓↓############

  #もとのピンが消えた場合、nullとあいて「情報が消されたという情報」は残す。
  belongs_to :drawing_pin, optional: true
  ####↑↑↑↑アソシエーション情報↑↑↑↑############

  def set_pin_info
    #「プランピン」作成時、
    pin_info = DrawingPin.find_by(id: self.drawing_pin_id)

    if pin_info.present?
      self.plan_pin_name = pin_info.pin_name
      self.plan_pin_article = pin_info.pin_article
      self.url = pin_info.url
    end

  end

end

app/controllers/plan_pins_controller.rb
class PlanPinsController < ApplicationController
  include GetPinForPlanShow
  include ChkAuthority

  before_action :authenticate_user!
  before_action :authenticate_users_info!

  def new
    #planのshow画面で開く、「まだプランに含まれていない吹き出し」
    #→これからプランに加えるかもしれない、という解釈で、「new」のパスを使用する。
    @drawing_pin = DrawingPin.find(params[:pin_id])
    @plan = Plan.find(params[:plan_id])
  end

  def show
    condition = {plan_pin_id: params[:id]}

    @plan_pin = select_pin_as_plan_member(condition)[0]
    @plan = Plan.find(params[:plan_id])
  end

  def create
    @plan_pin = PlanPin.new(plan_pin_params)
    # 処理後に対象ピンについての表示を再描写するため、ピン情報をインスタンス変数にセット
    # なお、「plan_pinの名前と記事セット」はモデル側（before_validation :set_pin_info）で行う
    set_drawing_pin(@plan_pin.drawing_pin_id)

    respond_to do |format|
      if @plan_pin.save
        flash[:notice] = t('activerecord.normal_process.messages.do_save_this_to',to_this: t('activerecord.models.plan') + "「#{@plan_pin.plan.plan_name}」",this: t('activerecord.models.drawing_pin') )
      else
        #エラー情報をフラッシュに保存
        flash[:danger] = @plan_pin.errors.full_messages
      end
      format.js { render '/drawing_pins/reset_index_and_bubble_item'}
    end
  end

  def create_in_planform

    @plan_pin = PlanPin.new(plan_pin_params)
    # 処理後に対象ピンについての表示を再描写するため、ピン情報をインスタンス変数にセット
    # なお、「plan_pinの名前と記事セット」はモデル側（before_validation :set_pin_info）で行う
    set_drawing_pin(@plan_pin.drawing_pin_id)

    respond_to do |format|
      if @plan_pin.save
        flash[:notice] = t('activerecord.normal_process.messages.do_save_this_to',to_this: t('activerecord.models.plan') + "「#{@plan_pin.plan.plan_name}」",this: t('activerecord.models.drawing_pin') )
      else
        #エラー情報をフラッシュに保存
        flash[:danger] = @plan_pin.errors.full_messages
      end

      format.js { render '/plans/reset_search_and_index'}
    end

  end

  def destroy
    # 削除時処理
    set_plan_pin_from_pin_and_plan
    # 処理後に対象ピンについての表示を再描写するため、ピン情報をインスタンス変数にセット
    set_drawing_pin(@plan_pin.drawing_pin_id)

    show_plan_name = @plan_pin.plan.plan_name

    @plan_pin.destroy

    respond_to do |format|
      flash[:notice] = t('activerecord.normal_process.messages.do_del_from',from_this: t('activerecord.models.plan') + "「#{show_plan_name}」",this: t('activerecord.models.drawing_pin') )
      format.js { render '/drawing_pins/reset_index_and_bubble_item'}
    end

  end

  def destroy_in_planform

    # 削除時処理
    @plan_pin = PlanPin.find(params[:id])
    show_plan_name = @plan_pin.plan.plan_name

    @plan_pin.destroy

    respond_to do |format|
      flash[:notice] = t('activerecord.normal_process.messages.do_del_from',from_this: t('activerecord.models.plan') + "「#{show_plan_name}」",this: t('activerecord.models.drawing_pin') )
      format.js { render '/plans/reset_search_and_index'}
    end

  end

  def edit
    set_plan_pin
    @form_name=t('activerecord.models.plan') + ":" + @plan_pin.plan.plan_name
    @form_name_sub="→" + t('activerecord.models.drawing_pin') + t('activerecord.normal_process.noun.update')

    if session["edit_plan_pin"].present?
      #session情報がある場合はそれを取得して、取得したsessionはクリアする（エラー発生によりredirect_toした場合の処理）
      @plan_pin = PlanPin.new(session["edit_plan_pin"])

      session["edit_plan_pin"] = nil
    end

  end

  def update
    set_plan_pin

    if @plan_pin.update(plan_pin_params)
    redirect_to edit_plan_plan_pin_path, notice: t('activerecord.normal_process.messages.do_update')
    else
      #入力情報をセッション、エラー情報をフラッシュに保存して
      session["edit_plan_pin"] = @plan_pin
      flash[:danger] = @plan_pin.errors.full_messages
      redirect_to edit_plan_plan_pin_path
    end

  end



private

  def set_plan_pin
    @plan_pin = PlanPin.find(params[:id])
  end

  def set_plan_pin_from_pin_and_plan
    @plan_pin = PlanPin.find_by(plan_id: params[:plan_pin][:plan_id],drawing_pin_id: params[:plan_pin][:drawing_pin_id])
  end

  def plan_pin_params
    params.require(:plan_pin).permit(:plan_id, :drawing_pin_id,:plan_pin_name,:plan_pin_article,:route,:url)
  end

  def set_drawing_pin(pin_id)
    @drawing_pin = DrawingPin.find(pin_id)
  end

  def authenticate_users_info!
    #プランピンのコントローラーでは、「属しているプランが自身（ログインユーザー）のプランかどうか」で権限チェック
    redirect_to err_path if not is_your_info?(model_name: Plan.name , model_id: params[:plan_id])
  end

end

app/helpers/plan_pins_helper.rb
module PlanPinsHelper

  #セレクトボックス作成のために、（引数がTならば現在ユーザーの）プラン情報を取得
  def get_routes_as_selectbox_info(has_blank: false)
  # def get_routes_as_selectbox_info(planpin_id: "", has_blank: false)

    # plan_pins = Plan.find(plan_id).order(:created_at)
    #
    # if only_currentuser
    #   plans = Plan.find(plan_id).order(:created_at)
    # else
    #   plans = Plan.all.order(:created_at)
    # end

    if has_blank==true
      box_info = (0..3).map{|route_type| [get_route_name(route_type),route_type]}.unshift(["",""])
    else
      box_info = (0..3).map{|route_type| [get_route_name(route_type),route_type]}
    end

    return box_info
        # return [box_info,planpin_id]

  end

  def get_route_name(route_type)

    case route_type

    when 0
      return "非表示"

    when 1
      return "直線"

    when 2
      return  "徒歩＋車"

    when 3
      return  "徒歩"

    else
      return "想定外の種類"
    end
  end

end

app/views/plan_pins/_new.html.erb
<%# 【planのshow画面】にて描写する「吹き出し」
……「まだ対象プランに含まれていない、ただのピン情報（プランピンではない）」を表示する
  ……これから含まれるかもしれないので、《候補→candidate》
↓
「インデックスのアイテム」になることはない %>

<% onmap = "_onmap" %>
<!-- <div class="index_grid_item"> -->
  <div class="index_grid_item_head<%= onmap %>">

    <% if pin.url.blank? %>
      <a ><%= pin.pin_name %></a>
    <% else %>
      <%= link_to pin.pin_name, pin.url , :target=>["_blank"] %>
    <% end %>
    
  </div>

  <div class="index_grid_item_body<%= onmap %>">

    <div class="index_grid_item_body_left<%= onmap %>" >

      <% if pin.image && pin.image.url %>
        <%= image_tag(pin.image.url,class: 'index_grid_item_imagecontent' + onmap)  %>
      <% else %>
        <a class="index_grid_item_imagecontent<%= onmap %>" ><%= t('activerecord.attributes.drawing_pin.no_image.no_image') %></a>
      <% end %>
    </div>

    <div class="index_grid_item_body_right<%= onmap %>">
      <div class="index_grid_item_body_maintext<%= onmap %>">
        <strong>【<%= t('noun.details') %>】：</strong><%= pin.pin_article %>
      </div>
    </div>
  </div>

  <div class="index_grid_item_line_1<%= onmap %>" >

  </div>

  <div class="index_grid_item_line_2<%= onmap %>" >
    <%= form_with model: PlanPin.new, method: :post , url: create_in_planform_plan_plan_pins_path(plan.id), remote: true do |form| %>

      <%= form.hidden_field :plan_id ,value: plan.id%>
      <%= form.hidden_field :drawing_pin_id ,value: pin.id  %>

      <a><%= t('activerecord.models.plan') %>:</a>
      <%= plan.plan_name + t('verb.to') %>
      <%= form.submit t('verb.add') ,class: "btn btn-primary btn-sm" %><%= t('verb.do') %>

    <% end %>

  </div>

app/views/plan_pins/_show.html.erb
<%# 【planのshow画面】にて描写する、
「インデックスのアイテム」および「吹き出し」
……「すでに対象プランに含まれているプランピン情報」を表示する %>
<%# item_type:「0」→グリッド欄のアイテム、「１」→地図上の吹きだし %>

<% if item_type == 0 %>

  <input name="latitude" type="hidden" data-target = "pin-and-planpin.latitude" value= <%= plan_pin.latitude %>  data-action-pin-id = <%= plan_pin.drawing_pin_id.to_s %> >
  <input name="longitude" type="hidden" data-target = "pin-and-planpin.longitude" value= <%= plan_pin.longitude %>  data-action-pin-id = <%= plan_pin.drawing_pin_id.to_s %> >

  <% onmap = "" %>

  <% else %>
  <% onmap = "_onmap" %>
<% end %>

<!-- <div class="index_grid_item"> -->
  <div class="index_grid_item_head<%= onmap %>">

    <% if plan_pin.url.blank? %>
      <a ><%= plan_pin.pin_name %></a>
    <% else %>
      <%= link_to plan_pin.pin_name, plan_pin.url , :target=>["_blank"] %>
    <% end %>
        
  </div>

  <div class="index_grid_item_body<%= onmap %>">

    <% if item_type == 0 %>
      <div class="index_grid_item_body_left<%= onmap %>" data-action = "click->pin-and-planpin#move" data-action-pin-id = <%= plan_pin.drawing_pin_id.to_s %> >
    <% else %>
      <div class="index_grid_item_body_left<%= onmap %>" >
    <% end %>

      <% if plan_pin.drawing_pin && plan_pin.drawing_pin.image && plan_pin.drawing_pin.image.url %>
        <%= image_tag(plan_pin.drawing_pin.image.url,class: 'index_grid_item_imagecontent' + onmap)  %>
      <% else %>
        <a class="index_grid_item_imagecontent<%= onmap %>" ><%= t('activerecord.attributes.drawing_pin.no_image.not_set') %></a>
      <% end %>
    </div>

    <div class="index_grid_item_body_right<%= onmap %>">
      <div class="index_grid_item_body_maintext<%= onmap %>">

        <% if item_type == 0 %>
          <strong>【<%= t('noun.details') %>】：</strong><%= plan_pin.pin_article.truncate(22) %>
        <% else %>
          <strong>【<%= t('noun.details') %>】：</strong><%= plan_pin.pin_article %>
        <% end %>

      </div>
    </div>
  </div>

  <div class="index_grid_item_line_1<%= onmap %>" >
    <% if plan_pin.drawing_pin  %>
      <%= link_to  t('activerecord.normal_process.noun.update') , edit_plan_plan_pin_path(plan_pin.plan_id,plan_pin.id) , class: "btn btn-primary btn-sm btn_edit_planpin#{onmap}" %>
    <% end %>

  </div>

  <div class="index_grid_item_line_2<%= onmap %>" >

    <%= form_with model: plan_pin, method: :delete , url: destroy_in_planform_plan_plan_pin_path(plan_pin.plan_id,plan_pin.id), remote: true do |form| %>

      <%# <%= form.hidden_field :plan_pin_id ,value: plan_pin.plan_pin_id %>

      <a><%= t('activerecord.models.plan') %>:</a>
      <% if item_type == 0 %>
        <%= plan.plan_name.truncate(10) %><%= t('verb.from') %>
      <% else %>
        <%= plan.plan_name %><%= t('verb.from') %>
      <% end %>
      <%= form.submit t('verb.del') ,class: "btn btn-primary btn-sm" %><%= t('verb.do') %>

    <% end %>
  </div>

app/views/plan_pins/edit.html.erb
<!-- メッセージとか -->
<p id="notice_msg"><%= render 'layouts/show_notice_msg' %></p>
<p id="danger_msg"><%= render 'layouts/show_danger_msg' %></p>

<%= form_with(model: @plan_pin , method: :patch , url: plan_plan_pin_path(@plan_pin.plan_id,@plan_pin.id), local: true) do |form| %>

<div class=""　 data-controller="edit-pin">

<div class="edit_twin_box">

  <div id = "edit_map_box"  class="edit_map_box" data-target="edit-pin.map" >
  <!-- ここに地図を描く -->
  </div>

  <div class="edit_image_box">
    <% if @plan_pin.drawing_pin.image && @plan_pin.drawing_pin.image.url %>
      <%= image_tag(@plan_pin.drawing_pin.image.url,class: 'edit_image_box_content')  %>
    <% else %>
      <h5 class="" >【<%= t('activerecord.attributes.drawing_pin.no_image.not_exist') %>】</h5>
    <% end %>
  </div>

</div>

<div class="line_info">
  <a class="line_content_1"><%= t('activerecord.attributes.drawing_pin.address') + ":" + @plan_pin.drawing_pin.address %>
     (<%= t('activerecord.attributes.drawing_pin.latitude') %>:<span data-target="edit-pin.latitude"><%= @plan_pin.drawing_pin.latitude %></span>
     、 <%= t('activerecord.attributes.drawing_pin.longitude') %>:<span data-target="edit-pin.longitude" ><%= @plan_pin.drawing_pin.longitude %></span>)</a>
</div>


<div class="line_info">
  <%= form.label "前の📍からの経路" ,class: "line_content_1" %>
  <%= form.select :route, get_routes_as_selectbox_info() , {:selected => @plan_pin.route},class: "line_content_2_large_interval"  %>
</div>

<div class="line_info">
  <%= form.label :plan_pin_name ,class: "line_content_1" %>
  <%= form.text_field :plan_pin_name ,class: "line_content_2_large_interval" ,maxlength: 30 %>
</div>

<div class="line_info_multiline">
  <%= form.label :plan_pin_article ,class: "line_content_1" %>
  <%= form.text_area :plan_pin_article,class: "line_content_2_large_interval input_text_content" ,maxlength: 180 %>
</div>

<div class="line_info">
  <%= form.label "リンク先（プラン用)" ,class: "line_content_1" %>
  <%= form.text_field :url ,class: "line_content_2_large_interval txt_pin_name" ,maxlength: 4096 %>
</div>

<div class="line_info">
  <%= form.submit t('activerecord.normal_process.noun.update') ,class: 'btn btn-primary btn_line_2' %>

</div>

</div>
<% end %>

app/views/plan_pins/new.js.erb
// planのshow画面で開く、「まだプランに含まれていない吹き出し」
// →これからプランに加えるかもしれない、という解釈で、「new」のパスを使用する。

$("#pin_id_<%= @drawing_pin.id%>_onmap").html("<%= j(render 'plan_pins/new', { pin: @drawing_pin ,plan: @plan}) %>");

app/views/plan_pins/show.js.erb
// planのshow画面で開く、「すでにプランに含まれているピン（＝プランピン」の情報
// →「show」のパスを使用して、内部で「削除」「更新画面への繊維」を行う

$("#pin_id_<%= @plan_pin.drawing_pin_id%>_onmap").html("<%= j(render 'plan_pins/show', {plan: @plan,plan_pin: @plan_pin ,item_type: 1  }) %>");
// item_type:「0」→グリッド欄のアイテム、「１」→地図上の吹きだし